#!/usr/bin/env bash
# why do we need comments
VAR1=$(grep -c -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+[[:space:]]+localhost' /etc/hosts)
if [ "$VAR1" -gt 0 ]; then
    sed -E 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+[[:space:]]+localhost/127.0.0.2  localhost/' /etc/hosts
else
    echo "127.0.0.2  localhost" >> /etc/hosts
fi
VAR2=$(grep -c -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+[[:space:]]+facebook.com' /etc/hosts)
if [ "$VAR2" -gt 0 ]; then
    sed -E 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+[[:space:]]+facebook.com/8.8.8.8  facebook.com/' /etc/hosts
else
    echo "8.8.8.8  facebook.com" >> /etc/hosts
fi
