#!/usr/bin/env bash
# why do we need comments
echo "----------------------------------"
cat /etc/hosts
VAR1=$(grep -c -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s+localhost' /etc/hosts)
if [ "$VAR1" -gt 0 ]; then
    sed -i -E 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s+localhost$/127.0.0.2  localhost/' /etc/hosts
else
    echo "127.0.0.2  localhost" >> /etc/hosts
fi
VAR2=$(grep -c -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s+facebook.com' /etc/hosts)
if [ "$VAR2" -gt 0 ]; then
    sed -i 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s+facebook.com$/8.8.8.8  facebook.com/' /etc/hosts
else
    echo "8.8.8.8  facebook.com" >> /etc/hosts
fi
echo "----------------------------------"
cat /etc/hosts
echo "----------------------------------"
